name: calendar_views
version: 1.0.1

description: Collection of customisable calendar related widgets for Flutter.

author: ZedTheLed<zedtheled@gmail.com>

homepage: https://github.com/ZedTheLed/calendar_views

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
